### ISSUE TITLE
[Design] AddPhrase에서 카테고리지정이랑 완료축하

### ISSUE THREAD

**Issue by morningfest** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#39]
## 🛠 Issue

구절추가에서 카테고리 지정이랑 완료 축하뷰 짜기
<img width="543" alt="스크린샷 2024-08-03 오후 4 10 38" src="https://github.com/user-attachments/assets/46705184-b250-4f3c-8f4b-4166efd51592">

## 📝 To-do

- [x] 리스트 복수선택하게 하는 거
- [x] 카테고리 추가하기뷰 짜기
- [x] 완성 축하 뷰 짜기
