### ISSUE TITLE
[Feat] 구리스에게 남은 업무들 처리

### ISSUE THREAD

**Issue by Guryss** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#61]
## 🛠 Issue
- 저에게 남은 업무들을 차근차근 처리해나가보겠습니다. 

## 📝 To-do

- [x] EditBook → DetailBook 으로 돌아갈 때 데이터 reload 필요
- [ ] Home 오늘의 추천빵 PhraseCard 구현
- [x] AddPhrase, EditPhrase, DetailPhrase 데이터 및 뷰 연결 구현
