### ISSUE TITLE
[Feat] 제리에게 남은 과제 수행

### ISSUE THREAD

**Issue by 3405000** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#62]
## 📝 To-do

- [ ] 구절 등록되었을 때 구절 개수 연결 확인하기
- [x] Clip, Book 정렬 기능 구현하기
- [x] 네비게이션 타이틀 중앙정렬
- [x] AddPhrase: Clip 추가하는 기능 구현하기
- [x] AddClip, EditClip: title, description 글자수 제한이 유저에게 보이도록하기
- [ ] PhraseCard 안에 빵 넣기

**Comment by 3405000** [comment]
AddClip, EditClip: title, description 글자수 제한이 유저에게 보이도록하기 : 
<img width="200" alt="image" src="https://github.com/user-attachments/assets/e20f76dc-642c-4a4f-bc93-b8e79f6f5c0e">

**Comment by Guryss** [comment]
오제리 최고!!!!!!!!!!!! **끼얏호!!!!!!!!!!!!!!!!!!!!!! 꺄약ㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱㄱ**

**Comment by morningfest** [comment]
보라돌이 파이팅🥧
