### ISSUE TITLE
[Feat] 개발 남은 업무 해치우기

### ISSUE THREAD

**Issue by Guryss** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#64]
## 🛠 Issue
- 개발 남은 업무들을 해치워보겠습니다. 

## 📝 To-do
- [x] 책빵사용설명서 → 이미지 붙이기 
- [x] 온보딩뷰 붙이기 → 책빵사용설명서 
- [x] AddClip: TextField 입력 후 밖에 클릭했을 때 키보드 내려가도록
- [x] AddClip: 기본 클립 일때 selected되어있도록
- [x] Phrase 데이터 내 page 삭제

**Comment by 3405000** [comment]
칭스
