### ISSUE TITLE
[Fix] 제리의 할거 박박많음쇼 (사실 그렇게 많지는 않음)

### ISSUE THREAD

**Issue by 3405000** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#66]
## 🛠 Issue

마지막가지 와이팅

## 📝 To-do

- [x] PhraseCard안에 빵 넣기
- [x] PhraseCard 텍스트 양 적을 때 중앙으로 밀리는 거 해결하기
- [x] PhraseCard를 .. 쪼개야한다면 쪼개기
- [x] 구절 수정창에서 클립 선택 변경하는 뷰 만들기
- [x] 책추가, 구절추가 완료 뷰에서 글자 위치 수정하기
- [x] 메인 화면에서 구절 하나도 없을 때 뜨는 뷰 만들기
- [x] 구절이 하나라도 있으면 구절 랜덤으로 보여주는 로직 짜기
- [x] 메인화면 상단바 왜 흰색 …? -> 배경 입혀주기
- [ ] (시간되면 할 것) 오늘의 빵 바로 보여주는 게 아니라 빵으로 먼저 감추어놨다가 터치하면 구절이 공개되면 좋겠다.

**Comment by Guryss** [comment]
할거박박박많지만 구리스와함께라면두렵지않잖아 제리제리
