### ISSUE TITLE
[Feat] 진짜진짜진짜리얼최종

### ISSUE THREAD

**Issue by Guryss** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#69]
## 🛠 Issue
- 진짜 최종으로 작업합니다. 끝끝끝

## 📝 To-do

- [x] LiveText 기능
- [ ] widget 기능
- [x] Home: 책 등록되지 않았을 때 등록 유도 UX writing 추가
- [x] Home: 오늘의 추천빵 랜덤으로 두두두둥장
- [x] DetailClip padding 조정
- [ ] Code 정리
