### ISSUE TITLE
[Feat] 빵수증 지대로 구현

### ISSUE THREAD

**Issue by 3405000** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#78]
## 🛠 Issue

빵수증을 제대로 ~ 구현하겠습니다!!

## 📝 To-do

- [x] 빵수증 기간 분류
- [x] 처음 들어갔을 때 기간 분류 중 가장 최근 거 선택되어야 함
- [x] 구절 데이터를 기간에 맞는 데이터로 필터링해 가져오기
- [ ] 빵수증에 뜨는 날짜를 앱 최초 설치일부터...
- [ ] 또 뭐가 있을까 …
- [x] 빵수증 내 순위 데이터 순서대로 보여지게 해야됨 (우선 그냥 순서없게 해뒀음)
- [x] 빵수증, 책, 클립, 구절 삭제 가능하게 -> 논의 필요해서 일단 빵수증만 삭제 가능하게 해둠
- [x] 클립상세페이지의 구절 카드 책 제목이 길어지면 좌우로 잘림현상 해결하기
