### ISSUE TITLE
[Feat] 빵수증 데이터 관련해서 수정 & 삭제기능

### ISSUE THREAD

**Issue by 3405000** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#83]
## 🛠 Issue

책, 구절, 클립, 빵수증 등 데이터가 삭제되었을 때 다른 데이터에 영향을 끼치지 않도록 조정합니다.

## 📝 To-do

- [x] 기존의 방식 : 빵수증 데이터 생성 시 책, 클립 데이터를 관계형으로 연결 -> 수정 방향 : 빵수증 데이터 생성 시 책, 클립 데이터를 복사해 저장. 빵수증 데이터의 무결성을 보장해주기 위함.
- [x] 책, 구절, 클립 삭제기능
- [ ] 구절 카드에서 맨위 텍스트인 책 제목 너무 길면 텍스트와 형광펜 두 줄로 보이게 하기. 시도 해보고 안되면 그냥 쩜쩜쩜으로 한줄로 하겠슴
- [x] 구절 카드에서 맨 아래 텍스트인 책 제목의 경우 너무 길면 잘림 -> 쩜쩜쩜으로 만들기
- [x] 오늘의 추천 빵 정해진 시간 되면 교체되게 하기 (내가.. 잘 할 수 있을가..?)
- [x] 오늘의 추천 빵 정해진 시간 되면 lock 되는 기능

**Comment by 3405000** [comment]
삭제기능 구현하긴 했는데 삭제하면 화면에 띄워지던 데이터가 nil이 되어서 앱이 멈춤 
ㅋㅋ
