### ISSUE TITLE
[Release] 릴리즈 2차 작업

### ISSUE THREAD

**Issue by Guryss** [DeveloperAcademy-POSTECH/2024-MC3-A17-ApplePuffGirls#87]
## 🛠 Issue

- 릴리즈 2차 작업을 진행합니다. 

## 📝 To-do

- [x] 뷰 전환 방식 수정 (NavigationStack)
- [x] 삭제 방식 수정
- [x] 데이터 없을 때 UI 수정
- [x] Live Text 기능 보완 및 UI 수정
- [x] 온보딩 swipe 기능 추가
